# Generated by Django 5.2.3 on 2025-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_notes_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_ws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
