# Generated by Django 5.2.3 on 2025-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_token_ws'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token_ws',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
