# Generated by Django 5.2.3 on 2025-06-30 06:51

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('BODEGUERO', 'Bodeguero'), ('CONTADOR', 'Contador'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', help_text='Rol del usuario', max_length=20),
        ),
    ]
